# Hey, thanks for using my theme. If you like this theme,checkout my repo (https://gitlab.com/avron/gruvhugo"
# and drop a star while you're at it. ;)
baseurl = "https://www.gout-is-shit.com/"
title = "Gout Is Shit (dot) Com"

languageCode = "en-us"
paginate = "10" # Number of posts per page
#disqusShortname = "" # Enable comments by entering your Disqus shortname
#googleAnalytics = "" # Enable Google Analytics by entering your tracking id
#-------------------------------------------------------------------------------
# DEFAULT SETTINGS
#-------------------------------------------------------------------------------

# Default Theme
theme= "gruvhugo"

# Default Post Extension
defaultExtension= "html"

# Default metadata format for newly created frontmatter using
# hugo new command. "toml", "yaml", or "json"
metaDataFormat= "yaml"

[markup.goldmark.renderer]
unsafe= true

[taxonomies]
  tag      = "tags"
  category = "categories"
  series   = "series"

[params.main]
  enabled = true
  name = "jane_doe"
  img = "img/author.jpg"
  # Thanks to Christina @ wocintechchat.com for this photo.
  icon = "img/logo.png"
  quote = "People wish their enemies dead - but I do not; I say give them the gout, give them the stone! - Mary Wortley Montagu"
  description= "Gout is horrible and you're not suffering alone."

 # Social icons
 #[[params.social]]
 #  name = "gitlab"
 #  url  = "https://gitlab.com/avron/gruvhugo"

 #[[params.social]]
 #  name = "email"
 #  url  = "mailto:mail@mail.com"

 #[[params.social]]
 #  name = "gpg"
 #  url  = "https://keys.openpgp.org/"

 #[[params.social]]
 #  name = "twitter"
 #  url  = "https://twitter.com/"

 #[[params.social]]
 #  name = "github"
 #  url  = "https://github.com/"

 #[[params.social]]
 #  name = "linkedin"
 #  url  = "https://www.linkedin.com/"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about"

  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "post/"

  [[menu.main]]
    identifier = "wiki"
    name       = "Wiki"
    url        = "none"
