---
name: master_push
on:
  push:
    branches:
      - main
jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: SetupHugo
        run: >
          curl -LO
          https://github.com/gohugoio/hugo/releases/download/v0.81.0/hugo_0.81.0_Linux-64bit.tar.gz

          tar -vzxf hugo_0.81.0_Linux-64bit.tar.gz

          chmod a+x hugo
      - name: Build
        run: ./hugo  --cleanDestinationDir  --gc
      - name: copy file via ssh password
        uses: up9cloud/action-rsync@master
        env:
          HOST: ${{ secrets.scphost }}
          USER: ${{ secrets.scpuser }}
          KEY: ${{ secrets.scpkey }}
          TARGET: /home/web/www.gout-is-shit.com/
          SOURCE: ./public/
